repos/EFC/Models/ErrorViewModel.cs
namespace EFC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

repos/EFC/Models/Kitap.cs
using System.ComponentModel.DataAnnotations;

namespace EFC.Models
{
    public class Kitap
    {
        [Key]
        public int KitapID { get; set; }
        [Required]
        [MaxLength(100)]
        [Display(Name ="Kitap Adı")]
        public string KitapAdi { get; set; }
        public int YazarID { get; set;}
        public Yazar Yazar { get; set; }
    }
}

repos/EFC/Models/KitaplikContext.cs
using Microsoft.EntityFrameworkCore;

namespace EFC.Models
{
    public class KitaplikContext : DbContext
    {
        public DbSet<Kitap> Kitaplar { get; set; }
        public DbSet<Yazar> Yazarlar { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb; Database=Kitaplik;Trusted_Connection=True;");
        }
    }
}

repos/EFC/Models/Yazar.cs
using System.ComponentModel.DataAnnotations;

namespace EFC.Models
{
    public class Yazar
    {
        public int YazarID { get; set; }
        [Required]
        [MaxLength(100)]
        [Display(Name ="Yazar Ad")]
        public string YazarAd { get; set; }
        [Required]
        [MaxLength(100)]
        [Display(Name ="Yazar Soyad")]
        public string YazarSoyad { get; set; }
        public ICollection<Kitap>Kitaplar { get; set; }
    }
}

repos/EFC/Controllers/HomeController.cs
using EFC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EFC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

repos/EFC/Controllers/YazarController.cs
using EFC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EFC.Controllers
{
    public class YazarController : Controller
    {
        public KitaplikContext k = new KitaplikContext();
        public IActionResult Index()
        {
            var m=k.Yazarlar.ToList();
            return View(m);
        }
        public IActionResult Create()
        {
            
            return View();
        }
    }
[HttpPost]
        public IActionResult Create(Yazar y)
        {
        if (ModelState.IsValid)
        {
            k.Add(y);
            k.SaveChanges();
            return RedirectToAction("index");
        }
        else
        {
            ViewBag.msj = "Yazar Eklenemedi!";
            return View(y);
        }
            
        return View;
        }

}

repos/EFC/Views/Home/Index.cshtml
<div class="row">
    <div class="col-md-4">
        <h2>Kitaplık Uygulaması</h2>
        <p>
            Kitaplık uygulaması
            Entity Framework Core ile
            Asp.Net core MVC Web uygulaması geliştirilmiştir.
        </p>
    </div>
    <div class="col-4">
        <h2>Yazarlar</h2>
        <p>Yazarlar bölümünde yazarlar eıkleyip, düzenleyebilirsiniz.</p>
    </div>
    <div class="col-4">
        <h2>Kitaplar</h2>
        <p>kitaplar bölümünde yazarlar eıkleyip, düzenleyebilirsiniz.</p>
    </div>
</div>

repos/EFC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yazar" asp-action="Index">Yazarlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kitap" asp-action="Index">Kitaplar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EFC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

repos/EFC/Views/Yazar/Create.cshtml
@model EFC.Models.Yazar

@{
    ViewData["Title"] = "Create";
}
@if (ViewBag.msj is not null)
{
    <h1>@ViewBag.msj</h1>

}

<h4>Yazar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="YazarAd" class="control-label"></label>
                <input asp-for="YazarAd" class="form-control" />
                <span asp-validation-for="YazarAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YazarSoyad" class="control-label"></label>
                <input asp-for="YazarSoyad" class="form-control" />
                <span asp-validation-for="YazarSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Yazar Ekle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

repos/EFC/Views/Yazar/Index.cshtml
@model IEnumerable<EFC.Models.Yazar>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Yeni Yazar Oluştur.</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.YazarAd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YazarSoyad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.YazarAd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YazarSoyad)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.YazarID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.YazarID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.YazarID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>